import { Inter } from "next/font/google";
import "./globals.css";
import StoreWrapper from "@/common/wrapper/storeWrapper";
import "@mantine/core/styles.css";
import { ColorSchemeScript, createTheme, MantineProvider } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const theme = createTheme({white:"#242220"});
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
      <StoreWrapper>
        <MantineProvider theme={theme}>
          {children}
        </MantineProvider>
      </StoreWrapper>
      </body>
    </html>
  );
}
